server:
  port: 8881
spring:
  ## 应用名
  application:
    name: config-client
  ## 获取配置文件配置
  cloud:
    config:
      label: master
      profile: local
      discovery:
        enabled: true
        service-id: config-server
    ## 消息跟踪
    bus:
      trace:
        enabled: true

  ## MQ配置
  rabbitmq:
    addresses: 192.168.65.128
    port: 5672
    username: test
    password: test
    virtual-host: test


## 集群配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

## 刷新时，关闭安全验证
management:
  security:
    enabled: false