server:
  port: 6303
spring:
  ## application name
  application:
    name: config-client
  ##
  cloud:
    config:
      label: master
      profile: local
      discovery:
        enabled: true
        service-id: config-server
    ## trace bus
    bus:
      trace:
        enabled: true

  ## MQ
  rabbitmq:
    addresses: 10.16.31.78
    port: 5672
    username: clyming
    password: clyming
    virtual-host: clyming


## eureka registe
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/

## close authorized check
management:
  security:
    enabled: false