server:
  port: 6301
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JohnsonTay/springcloud-config/
          searchPaths: learn
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/